---
title: "Home"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---

## Table of content

### Figures

- [F1: Compositional data analysis, cluster-based](./figure_compositional.html)
- [F2: Compositional data analysis, cluster-free](./figure_compositional_cf.html)
- [F3 and S1: Expression change magnitudes, cluster-based](./figure_expression_shifts.html)
- [F4 and S2: Analysis of sample heterogeneity](./figure_heterogeneity.html)
- [F5 and S3: Differential Expression analysis](./figure_cluster_based_de_bio.html)
- [F6 and S4: Gene expression analysis, cluster-free](./figure_cluster_free_expression.html)
- [F7: Functional interpretation](./figure_interpretation.html)

### Preprocessing

- [Dataset preprocessing](./preprocess.html)
- [Cacoa preprocessing](./prepare_cacoa_results.html)

### Simulations

- [Simulations for different cell types](./simulation_types.html) *(also generates the necessary data)*
- [Simulations for num. of cells and num. of samples](./simulation_ns_nc.html)
- [Simulation for sensitivity to DE fraction change](./simulation_sensitivity_frac.html)
- [Simulation for sensitivity to log2-fold change](./simulation_sensitivity_lfc.html)
- [Different normalization types](./simulation_distances.html)

### Individual dataset reports

- [Alzheimer](./report_az.html)
- [Autism](./report_asd.html)
- [Epilepsy](./report_ep.html)
- [Multiple Sclerosis](./report_ms.html)
- [Pulmonary Fibrosis](./report_pf.html)
- [Squamous Cell Carcinoma](./report_scc.html)

## Data preparation

To download the raw data, you need to run `Rscript ./code/download_data.R` from the project folder.
After that, you need to run two scripts from the 'Preprocessing' section:
first [dataset preprocessing](./preprocess.html) and then [Cacoa preprocessing](./prepare_cacoa_results.html).
