---
title: 'Squamous Cell Carcinoma Dataset Report'
date: "`r Sys.Date()`"
author: "[Viktor Petukhov](https://github.com/VPetukhov/)"
output:
  html_notebook:
    toc: yes
    toc_depth: '3'
    toc_float: true
    df_print: paged
---

[*Publication*](https://www.sciencedirect.com/science/article/pii/S0092867420306723)

```{r libs, include=FALSE, message=FALSE}
library(cacoa)
library(dataorganizer)

library(ggplot2)
library(dplyr)
library(cowplot)
library(Matrix)
library(dplyr)
library(magrittr)
library(readr)
library(org.Hs.eg.db)

theme_set(theme_bw())
```

```{r, message=FALSE, warning=FALSE}
cao <- read_rds(DataPath("SCC/cao.rds")) %>% Cacoa$new()
cao$sample.groups.palette %<>% .[c(2, 1)]
cao$plot.params <- list(size=0.1, alpha=0.1, font.size=c(2, 3))
```

## Dependency on metadata

```{r, fig.width=8, fig.height=4}
lapply(c("coda", "expression.shifts"), function(sp) {
  cao$plotSampleDistances(space=sp, legend.position=c(1, 1))
}) %>%
  plot_grid(plotlist=., ncol=2, labels=c("CoDA", "Expression"), hjust=0, label_x=0.02, label_y=0.99)
```

The publication did not report any metadata, so we can not analyze it.

## Compositional differences

### Cluster-based

```{r}
# exc_samps <- rownames(cao$test.results$coda$cnts) %>% setdiff(rownames(cao_old$test.results$coda$cnts))
exc_samps <- c("P4_Normal", "P8_Normal", "P3_Tumor")
cao$estimateCellLoadings(samples.to.remove=exc_samps)
cao$plotCellLoadings()
```

```{r}
exc_samps <- c("P4_Normal", "P3_Tumor")
cao$estimateCellLoadings(samples.to.remove=exc_samps)
cao$plotCellLoadings()
```

```{r}
cao$plotCellLoadings()
```

```{r}
cao$plotContrastTree()
```

### Cluster-free

```{r, fig.width=5, fig.height=5}
g0 <- cao$plotEmbedding(color.by='cell.groups')
g0
```

KDE-based:

```{r, fig.width=8, fig.height=4.5}
cao$plotCellDensity(name='cell.density.kde') %>% plot_grid(plotlist=., ncol=2)
```

```{r, fig.width=8, fig.height=4}
plot_grid(g0, cao$plotDiffCellDensity(name='cell.density.kde', legend.position=c(0, 1)), ncol=2)
```

Graph-based:

```{r, fig.width=8, fig.height=4.5}
cao$plotCellDensity(name='cell.density.graph') %>% plot_grid(plotlist=., ncol=2)
```

```{r, fig.width=8, fig.height=4}
plot_grid(g0, cao$plotDiffCellDensity(name='cell.density.graph', legend.position=c(0, 1)), ncol=2)
```

## Expression differences

### Cluster-based

All genes:

```{r}
cao$plotExpressionShiftMagnitudes()
```

Top DE genes:

```{r}
cao$plotExpressionShiftMagnitudes(name='es.top.de')
```

### Cluster-free

```{r, fig.width=8, fig.height=4}
cao$plotClusterFreeExpressionShifts(legend.position=c(0, 1), font.size=c(2, 3))
```

## Functional interpretation

```{r, fig.width=10, fig.height=12, warning=FALSE, message=FALSE}
cao$plotVolcano(xlim=c(-3, 3), ylim=c(0, 3.5), lf.cutoff=1)
```

```{r, fig.width=8, fig.height=8}
cao$plotOntologyHeatmapCollapsed(name="GSEA", genes="all", n=30, clust.method="ward.D")
```

```{r}
cao$estimateGenePrograms(method="leiden", z.adj=TRUE, smooth=FALSE)
```

```{r, fig.width=12, fig.height=12}
cao$plotGeneProgramScores(
  legend.position=c(0, 1), plot.na=FALSE, 
  adj.list=theme(legend.key.width=unit(8, "pt"), legend.key.height=unit(12, "pt"))
)
```
